def electrical_engineering_lib():
    print("1. Ohms Law")
    print("2. Electrical Power")
    print("3. Power Current")
    print("4. Power Voltage")
    print("5. Electrical Energy")
    print("6. Series Resistance")
    print("7. Parallel Resistance")
    print("8. Conductance")
    print("9. Voltage Divider")
    print("10. Current Divider")
    print("11. Frequency")
    print("12. Period")
    print("13. Capacitive Reactance")
    print("14. Inductive Reactance")
    print("15. Impedance")
    print("16. Kirchhoff's Voltage Law")
    print("17. Kirchhoff's Current Law")
    print("18. Coulombs Law")
    print("19. Electric Field")
    print("20. Electric Potential")

    print("")
    print("0. Exit")
    print("")