def linear_algebra_lib():
    print("1. Dot Product")
    print("2. Vector Magnitude")
    print("3. Unit Vector")
    print("4. Vector Addition")
    print("5. Vector Subtraction")
    print("6. Scalar Multiplication")
    print("7. Cross Product")
    print("8. Matrix Addition")
    print("9. Matrix Subtraction")
    print("10. Matrix Multiplication")
    print("11. Matrix Transpose")
    print("12. 2x2 Determinant")
    print("13. Matrix Trace")
    
    print("")
    print("0. Exit")
    print("")