def linear_algebra_lib():
    print("1. Dot Product")
    print("2. Vector Magnitude")
    print("3. Unit Vector")
    print("4. Vector Addition")
    print("5. Vector Subtraction")
    print("6. Scalar Multiplication")
    print("7. Cross Product")
    print("8. Matrix Addition")
    print("9. Matrix Subtraction")
    print("10. Matrix Multiplication")
    print("11. Matrix Transpose")
    print("12. 2x2 Determinant")
    print("13. Matrix Trace")
    print("14. Matrix Inverse")
    print("15. Matrix Rank")
    print("16. Reduced Row Echelon Form (RREF)")
    print("17. Matrix Determinant (NxN)")
    print("18. Angle Between Vectors")
    print("19. Vector Projection")
    print("20. Distance Between Vectors")
    print("21. Eigenvalues")
    print("22. Eigenvectors")
    print("23. Characteristic Polynomial")
    print("24. Null Space")
    print("25. Column Space")
    print("26. Row Space")
    print("27. Gram-Schmidt Orthogonalization")
    print("28. Linear Independence Test")
    print("29. LU Decomposition")
    print("30. QR Decomposition")
    print("31. Matrix Norm")
    print("32. Orthogonal Matrix Check")
    print("33. Symmetric Matrix Check")
    print("34. Skew-Symmetric Matrix Check")
    print("35. Diagonalization Check")

    print("")
    print("0. Exit")
    print("")