def menu():
    print("╔══════════════════════════════════════════════╗")
    print("║      MATHEMATICAL COMPUTATION TERMINAL       ║")
    print("║               Version 1.0.0                  ║")
    print("╠══════════════════════════════════════════════╣")
    print("║ Status           : ONLINE                    ║")
    print("║ Formula Modules  : 7 Loaded                  ║")
    print("║ Constant Library : Loaded                    ║")
    print("║ Formula Database : Ready                     ║")
    print("╠══════════════════════════════════════════════╣")
    print("║                                              ║")
    print("║  [1] Algebra                                 ║")
    print("║  [2] Calculus                                ║")
    print("║  [3] Constants                               ║")
    print("║  [4] Conversions                             ║")
    print("║  [5] Geometry                                ║")
    print("║  [6] Physics                                 ║")
    print("║  [7] Statistics                              ║")
    print("║  [8] Linear Algebra                          ║")
    print("║                                              ║")
    print("║  [0] Exit                                    ║")
    print("║                                              ║")
    print("╚══════════════════════════════════════════════╝")
    print("")